# Generated by Django 3.0.4 on 2020-04-08 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200407_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
