# Generated by Django 3.0.4 on 2020-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20200408_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='comment',
            field=models.CharField(blank=True, default='a', max_length=200, null=True),
        ),
    ]
