# Generated by Django 3.0.4 on 2020-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20200415_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='Newcomment',
            field=models.CharField(blank=True, default='a', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='comment',
            field=models.CharField(blank=True, default='コメントしてね', max_length=200, null=True),
        ),
    ]
