# Generated by Django 3.0.4 on 2020-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20200415_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='commentuser',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
