# Generated by Django 3.0.4 on 2020-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_boardmodel_commentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField()),
                ('hobby', models.CharField(max_length=100)),
                ('occupation', models.TextField()),
                ('Residence', models.CharField(max_length=100)),
                ('myimages', models.ImageField(upload_to='')),
            ],
        ),
    ]
