# Generated by Django 3.0.4 on 2020-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_myprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='Residence',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='hobby',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
