# Generated by Django 3.0.4 on 2020-04-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_auto_20200418_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='occupation',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
