# Generated by Django 3.0.4 on 2020-04-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_auto_20200418_0732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProfile',
            new_name='MyProfileModel',
        ),
    ]
