# Generated by Django 3.0.4 on 2020-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_auto_20200421_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofilemodel',
            name='listofcreators',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='listofcreators',
            field=models.CharField(blank=True, default='a', max_length=300, null=True),
        ),
    ]
