# Generated by Django 3.0.4 on 2020-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0015_remove_boardmodel_listofcreators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekkuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ploftext', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
