# Generated by Django 3.0.4 on 2020-04-26 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0016_chekkumodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChekkuModel',
        ),
        migrations.RemoveField(
            model_name='myprofilemodel',
            name='author',
        ),
        migrations.AddField(
            model_name='myprofilemodel',
            name='name',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='boardapp.BoardModel'),
            preserve_default=False,
        ),
    ]
